### ISSUE TITLE
Make the default export `Promise`?

### ISSUE THREAD

**Issue by ljharb** [stefanpenner/es6-promise#108]
It's a bunch of boilerplate (and defies typical npm module convention) to do `require('something')` and then have `.somethingElse` after it.

Is there any reason that `require('es6-promise')` couldn't be `Promise` itself, and then you could stick `.polyfill` etc on it? That would make the typical usage be less boilerplatey, and still allow for a `polyfill` method.

This would require a major version bump. If you're open to it, I'd be happy to make a PR.

**Comment by stefanpenner** [comment]
> Is there any reason that require('es6-promise') couldn't be Promise itself, and then you could stick .polyfill etc on it? That would make the typical usage be less boilerplatey, and still allow for a polyfill method.

the downside is Promise doesn't have `.polyfill` so introducing it seems unfortunate. Ultimately, I am somewhat indifferent, I would love to hear @jakearchibald's thoughts. I will do what he prefers :)

**Comment by ljharb** [comment]
That's true - but when calling the method `polyfill`, it could delete itself from `Promise` before installing it on the global, and technically, the spec allows extensions to `Promise` anyways :-)

**Comment by stefanpenner** [comment]
`maybe _polyfil ?`

**Comment by ljharb** [comment]
I don't see how that would help - publicly exposed is exposed, a leading "_" in no way makes it public (see io.js v2.1.0's breakage via the request module removing a "_"-prefixed property).

If it's non-enumerable on `Promise`, I don't really see the problem - people are unlikely to `getOwnPropertyNames` on it, and it'd be removed when installed on the global.

**Comment by jakearchibald** [comment]
Could have `require('es6-promise/polyfill')` or similar for the polyfill?

I thought the use of es6 modules meant `require('whatever')` could only return an object, or has that changed?

**Comment by stefanpenner** [comment]
> Could have require('es6-promise/polyfill') or similar for the polyfill?

you raise a very good point!

**Comment by stefanpenner** [comment]
> I thought the use of es6 modules meant require('whatever') could only return an object, or has that changed?

nope, anything should be possible.

**Comment by stefanpenner** [comment]
for globals, likely can't do anything.

for AMD world, we can add:

```js
  define('es6-promise', [], function() { return Promise; });
  define('es6-promise/polyfil', function() { return polyfill; });
```

for node/cjs, we would need to insert additional files to have the same interface.

**Comment by stefanpenner** [comment]
I don't really have any extra moments right not to play with this, if someone else is included they are welcome to submit a PR

**Comment by stefanpenner** [comment]
i plan to make 4.0 have this functionality
