### ISSUE TITLE
Promise.race - support 3rd-party thenables

### ISSUE THREAD

**Issue by altano** [stefanpenner/es6-promise#110]
_this bug was split out of https://github.com/jakearchibald/es6-promise/issues/77_

I'm getting test failures when I use a promise other than an ES6 Promise in the iterable, e.g. this test fails:

```javascript
var ES6Promise = require("es6-promise").Promise;
var BlueBirdPromise = require("bluebird");
var assert = require("assert");

specify('the race begins on nextTurn and prioritized by array entry', function (done) {
    var firstResolver, secondResolver, nonPromise = 5;

    var first = new BlueBirdPromise(function (resolve, reject) {
        resolve(true);
    });

    var second = new BlueBirdPromise(function (resolve, reject) {
        resolve(false);
    });

    ES6Promise.race([first, second, nonPromise]).then(function (value) {
        assert.equal(value, true);
        done();
    });
});
```

This test is in the es6-promise test suite, except it uses ES6Promises for first and second and passes.

It is worth noting that the spec doesn't make any claims about prioritizing by array entry as far as I can tell, so I think it's the test itself that is incorrect, but I might be missing something.

**Comment by stefanpenner** [comment]
Will take a look

**Comment by stefanpenner** [comment]
Sorry it has been so long, this issue has slipped my mind.

Interestingly, if you replace bluebird with native promise. The issue goes away.

**Comment by stefanpenner** [comment]
Interestingly, this is also an issue with subclasses. EG. a subclass appears to favor its own instances during a "tie"

**Comment by stefanpenner** [comment]
this may be by design, but let me share why so others can chime in:

given the implementation of race is basically the following:
```js
var Constructor = this;
for (let promise in promises) {
 Constructor.resolve(promise).then(fulfilled, rejected);
}
```

and resolve acting as an identity if the promise has the same constructor

```js
function resolve(promise) {
  if (promise && typeof promise === 'object' && promise.constructor === this) {
    return promise;
  } else {
    // wrap because it is considered a foreign thenable.
  }
}
```

foreign thenables appear to always at best "join the race" after an additional turn.
