### ISSUE TITLE
Cannot load es6-promise module

### ISSUE THREAD

**Issue by alexmgarcia** [stefanpenner/es6-promise#138]
Hi,
I am trying to use es6-promise in an android hybrid app (targeting version 4.0+). This way I need an ECMAScript 6 Promise implementation.
However, when I am trying to load the module (in a browser) with `require('es6-promise')`, I get this error: `Error: Cannot find module 'es6-promise`

I can load other modules such as `data-structures` module (https://github.com/chenglou/data-structures and the require function is provided by data-structures bundle)

Here is the code snippet that I am using for loading the module:
`var Promise = require('es6-promise').Promise;`

Am I missing something or this shouldn't happen?

**Comment by stefanpenner** [comment]
I don't believe this to be an issue with this library. My guess is that https://github.com/chenglou/data-structures/blob/master/package.json must include es6-promise as a dependency.

something like:

```
npm install --save es6-promise
```

If I have misread, please correct me and I can reopen

**Comment by Flourad** [comment]
@stefanpenner i also encountered the same problems~

**Comment by stefanpenner** [comment]
@Flourad can you provide steps to reproduce?
