### ISSUE TITLE
Unhandled Rejection Event

### ISSUE THREAD

**Issue by dylanpyle** [stefanpenner/es6-promise#168]
I don't know the workings of whatwg particularly well, but it seems like this change introduced a global `unhandledrejection` event to the HTML spec: https://github.com/whatwg/html/pull/224

This seems like something that's worth implementing here proactively - it's a super important feature and probably one of the core reasons people end up choosing a "non-spec" Promise implementation like RSVP or Bluebird.

Feel free to close if I'm misunderstanding that proposal!

**Comment by dylanpyle** [comment]
Also: seems like newer versions of (at least) Chrome already implement this:

![screen shot 2016-02-23 at 12 52 25 pm](https://cloud.githubusercontent.com/assets/806257/13266290/2b1b28e4-da2c-11e5-8418-7dde751987cb.png)

**Comment by stefanpenner** [comment]
dupe: https://github.com/stefanpenner/es6-promise/issues/70
