### ISSUE TITLE
Promise.all is not a function

### ISSUE THREAD

**Issue by sykesd** [stefanpenner/es6-promise#181]
I receive this error on Chrome 49.0.2623.87. I have es6-promise 3.2.1.
I am packaging using webpack. Testing using the webpack development server. es6-promise is being included in webpack as a plugin:

    plugins: [
        new webpack.ProvidePlugin({
            "Promise": "es6-promise",
            "fetch": "imports?this=>global!exports?global.fetch!whatwg-fetch"
        })
    ]

The call in my code (TypeScript) looks like:

                return Promise.all(<Promise<any>[]> [CartService.find(), CatalogService.find()]);

`CartService.find()` and `CatalogService.find()` both return `Promise`s.

When my code runs I receive the error:

    Uncaught (in promise) TypeError: Promise.all is not a function

Looking at the JS sent to the browser I can see that this library is included in the bundled code.

If I comment out the line in my `webpack.config.js` file then it runs fine (but there is obviously no polyfill). 

What am I doing wrong?

**Comment by Sinewyk** [comment]
RTFM =D https://github.com/stefanpenner/es6-promise#nodejs

requiring es6-promise does not return a promise https://github.com/stefanpenner/es6-promise/blob/master/dist/es6-promise.js#L943-L946, it returns an object containing the `Promise` property with the Promise implementation and the `polyfill` property with the polyfill method.

**Comment by Sinewyk** [comment]
Just created https://www.npmjs.com/package/es6-promise-promise if it helps to avoid configuration problem when using webpack and other trick to replace/inject es6-promise which doesn't actually exports a promise ..

**Comment by stefanpenner** [comment]
@Sinewyk any recommendations for improving this for this repo?

**Comment by Sinewyk** [comment]
Yeah, somewhere around here https://github.com/stefanpenner/es6-promise/blob/master/lib/es6-promise/promise.js#L154 I would `Promise.Promise = Promise` and `Promise.polyfill = #attachPolyfill` and then I would simply exports the Promise itself.

Most people then could just use the exported Promise implementation, and for those not aware that the exports change, there's still the "public" API of something with a `polyfill` and `Promise` property attached so we don't break compatibility.

**Comment by stefanpenner** [comment]
Sounds reasonable. Pr?

**Comment by Sinewyk** [comment]
PR opened https://github.com/stefanpenner/es6-promise/pull/197
