### ISSUE TITLE
how to assign results of promise to global scope variable

### ISSUE THREAD

**Issue by vivekbrahmadandi** [stefanpenner/es6-promise#182]
How can we resolve promise to a normal number value .

I have use case in protractor automation in the first i have to call a asynchronous operation then that result value which should not be a promise .

I am using protractor framework

var mobileNumber = database.generateMobileNumber().then(function(mobileNumber){
    done();
    return mobileNumber;
}); 
var number=Promise.resolve(mobileNumber);

**Comment by stefanpenner** [comment]
the only way in ES3/ES5 is to invoke `then` on a promise. In the future, async/await will allow what appears to be synchronous access.

**Comment by ZeeshanAhmadKhalil** [comment]
Is there any way to access the promise data outside it or outside then() ?
