### ISSUE TITLE
Auto-polyfill

### ISSUE THREAD

**Issue by Andarist** [stefanpenner/es6-promise#183]
I've wanted to use this module as a module - I cannot trash global namespace and unfortunately it is auto-polyfilling window by default, although documentation seems to indicate something else.

Is there any good workaround for this now?

The best solution I've found so far is:

`import Promise from 'es6-promise/lib/es6-promise/promise'`

but it is hardcoding project structure and I dont really like that.

**Comment by mbleigh** [comment]
This is a serious problem. The docs seem to explicitly imply that polyfill is opt-in, but it's not.

**Comment by stefanpenner** [comment]
4.0 will include two builds

**Comment by Andarist** [comment]
Is there any estimate when 4.0 will ship?
