### ISSUE TITLE
"constructor is undefined" errors

### ISSUE THREAD

**Issue by anthonygreen** [stefanpenner/es6-promise#186]
I get 'constructor is undefined' errors when chaining Promises with older versions of IE 

    var promise = new Promise(function(resolve, reject) {
    …
    }).then(function() {
       return new Promise(function(resolve, reject) {
        …
       });
    });

**Comment by stefanpenner** [comment]
Which ie and which version of this library. Can you also provide a reproduction, maybe a jsbin?

**Comment by anthonygreen** [comment]
I've tried the tests with an alternative Promises library https://www.promisejs.org/ and this one does work

**Comment by stefanpenner** [comment]
I'm pretty sure this one also work ;)
