### ISSUE TITLE
Is this code unusable?

### ISSUE THREAD

**Issue by guotie** [stefanpenner/es6-promise#188]
In then.js, line 18-20

```
  if (child[PROMISE_ID] === undefined) {
    makePromise(child);
  }
````

here, child[PROMISE_ID] should NOT be undefined.

**Comment by stefanpenner** [comment]
> here, child[PROMISE_ID] should NOT be undefined.

well, it could be.

`Promise.prototype.then.call(otherThingWithoutPromiseId)` which is strange but legal

**Comment by stefanpenner** [comment]
https://github.com/stefanpenner/es6-promise/blob/master/test/extension-test.js#L45 i think covers these
