### ISSUE TITLE
Differing behavior from native Promises

### ISSUE THREAD

**Issue by rikshot** [stefanpenner/es6-promise#190]
```
var foo = Promise.resolve();
var bar = Promise.resolve();

foo.then(bar).then(() => console.log('first'));
Promise.all([foo, bar]).then(() => console.log('second'));
```

When global Promise object is native (tested in Node 6.1.0, Chromium Version 49.0.2623.108 and Firefox 46.0):
```
first
second
```

When global Promise object is from es6-promise.js:
```
second
first
```

**Comment by stefanpenner** [comment]
Ya seems strange, although i'm curious about what you expect `foo.then(bar)` to do?

**Comment by rikshot** [comment]
This occurred in testing code that was mocking promise chains with Promise.resolve(), so I guess it's not a mistake.

This happens on native Promise object too:

test1:
```
var foo = Promise.resolve();
var bar = Promise.resolve();
var baz = Promise.resolve();

foo.then(bar).then(baz).then(function() { console.log('zero') });
Promise.all([foo, bar]).then(function() { console.log('first') });
Promise.all([foo, bar]).then(function() { console.log('second') });
Promise.all([foo, bar, baz]).then(function() { console.log('third') });
```

test2:
```
var foo = Promise.resolve();
var bar = Promise.resolve();
var baz = Promise.resolve();

foo.then(bar).then(function() { console.log('zero') });
Promise.all([foo, bar]).then(function() { console.log('first') });
Promise.all([foo, bar]).then(function() { console.log('second') });
Promise.all([foo, bar, baz]).then(function() { console.log('third') });
```

test1 on native Promise object:
```
first
second
third
zero
```

test2 on native Promise object:
```
zero
first
second
third
```

Makes me think this is unspecified/undocumented behaviour, although I'm not sure. I did some reading of the Promise specification and it doesn't seem to dictate this at all.

**Comment by stefanpenner** [comment]
@rikshot no this is most likely a bug.

But in-addition to that, your example doesn't seem right: 

```
foo.then(bar).then(baz).then(function() { console.log('zero') });
```

i think you mean

```js
foo.then(() => bar).then(() => baz).then(function() { console.log('zero') });
```

**Comment by rikshot** [comment]
You're right, and that actually changes the order so that the original "bug" now prints
```
second
first
```
when using a native Promise object and es6-promise.

**Comment by stefanpenner** [comment]
@rikshot ya, non-theless i'll dig into the difference you pointed out as time permits.

**Comment by rikshot** [comment]
I'm still trying to figure out a minimal repro case for the original failure. While your correction fixed the repro that started this, it did not fix the problem in our testing code. When I use Promise.all and es6-promise, it fails. When I use Promise.all with native promises, it works as expected.

**Comment by unional** [comment]
Should it be an issue? The order should be non-deterministic. No consuming code should rely on any specific calling order.

There is no guarantee that ALL platform would behave the same way either.

My two cents. 🌷

**Comment by stefanpenner** [comment]
i keep forgetting to investigate this one. GH really needs a "mark as unread" or something :P .... adding this to my todolist.

@unional is this ambiguous in the spec, or merely userland shouldn't be so picky? (I will double check the spec this weekend when i have some time, as it isn't fresh in my memory so if i say anything I will most likely be making it up :P)

**Comment by unional** [comment]
```js
foo.then(bar).then(baz).then(function() { console.log('zero') });
Promise.all([foo, bar]).then(function() { console.log('first') });
Promise.all([foo, bar]).then(function() { console.log('second') });
Promise.all([foo, bar, baz]).then(function() { console.log('third') });
```
all `.then(function() ...)` are not tracked by `foo`, `bar`, `baz` and `Promise.all()` calls. The order "depends on" when `foo`, `bar`, `baz` and `Promise.all()` are ready.

The fact that `foo`, `bar`, `baz` are `Promise.resolve()` is a special case that IMO user should not rely on for the execution sequence.

However that being said, it would be nice to make `es6-promise` follows:

> Node 6.1.0, Chromium Version 49.0.2623.108 and Firefox 46.0

But I think it is not really a bug per se. 🌷

**Comment by stefanpenner** [comment]
> You're right, and that actually changes the order so that the original "bug" now prints
> 
> second
> first
> when using a native Promise object and es6-promise.

just tested it, it is `first` -> `second`.

**Comment by stefanpenner** [comment]
Just tested:

```
const foo = Promise.resolve();
const bar = Promise.resolve();
const baz = Promise.resolve();

foo.then(x => bar).then(y => baz).then(() => console.log('zero'))

Promise.all([foo, bar]).then(() => console.log('first'));
Promise.all([foo, bar]).then(() => console.log('second'));
Promise.all([foo, bar, baz]).then(() => console.log('third'));
```

ES6Promise
```
first
second
third
zero
```

Native

```
first
second
third
zero
```
