### ISSUE TITLE
library not found when using typescript

### ISSUE THREAD

**Issue by flyon** [stefanpenner/es6-promise#227]
Im trying to use this library with typescript, but the typescript compiler says: `Cannot find module 'es6-promise' `

The editor hints that `[...]node_modules/es6-promise/dist/es6-promise.js is not a module`

Any idea why it is not seen as a module?

I've done `npm install es6-promise`

My typescript source `test.ts`:
```
declare var require:any;
import {Promise,polyfill} from 'es6-promise';
polyfill();
Promise.resolve('success').then(console.log);
```

`tsc test.ts` gives an error: `test.ts(2,32): error TS2307: Cannot find module 'es6-promise'.`
but still compiles index.js:

```
"use strict";
var es6_promise_1 = require('es6-promise');
es6_promise_1.polyfill();
var x = es6_promise_1.Promise.resolve('success').then(console.log);
```

which is correct, and thus `node index.js` still runs correctly, but it would be nice if typescript wouldt give errors

**Comment by LOZORD** [comment]
It might be useful to use [Typings](https://github.com/typings/typings) instead of declaring your own. That's what I do 😄

**Comment by stefanpenner** [comment]
typings will go out with the next release, i suspect it will "just work" then
