### ISSUE TITLE
Missing newline at end of es6-promise.js

### ISSUE THREAD

**Issue by geroyche** [stefanpenner/es6-promise#244]
We're using concatenation tools to merge our bower dependencies. The missing newline at the end of es6-promise.js breaks this process (the subsequent file starts with a comment indicator _/*!_ which gets concatenated to the comment //# sourceMappingURL=es6-promise.map ), making the next line invalid

**Comment by stefanpenner** [comment]
@geroyche which concatenator?

**Comment by geroyche** [comment]
Grunt contrib concat.
Not sure it's really relevant though. 
Adding an enter character at the end of the file does fix the issue.

**Comment by stefanpenner** [comment]
> Not sure it's really relevant though.

I was curious, as most of the concat scripts I have worked on explicitly add a newline do to this ambiguity.

**Comment by geroyche** [comment]
Ah,  ok :)

**Comment by stefanpenner** [comment]
@geroyche I believe this to be a bug in grunt contrib concat, but I can also make this code more resilient. How about a trade, open an issue there so it is on there radar and I will make our concatenator more defensive.

**Comment by stefanpenner** [comment]
https://github.com/ef4/fast-sourcemap-concat/pull/27
