### ISSUE TITLE
JSPM support

### ISSUE THREAD

**Issue by davidpronk** [stefanpenner/es6-promise#248]
After installing es6-promise through JSPM, `main` is mapped to `dist/es6-promise.js`. but `dist` itself is not present. Only it's contents.
This can be solved by adding some JSPM config to the package.json. Setting jspm.directories to "lib": "dist" does the trick. I'll create a PR.

**Comment by stefanpenner** [comment]
> main is mapped to dist/es6-promise.js. but dist itself is not present. Only it's contents.

Can you explain this a bit more? `dist/*` should be bundled

**Comment by davidpronk** [comment]
@stefanpenner JSPM does not install the entire bundle but just the content of dist because of the directories.lib configuration in the package.json
```
"directories": {
    "lib": "lib"
  },
```
[JSPM documentation on directories.lib](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#directorieslib)

**Comment by stefanpenner** [comment]
This seems to have gone stale. I would be open to a  PR making it easier to use system-js.
