### ISSUE TITLE
Error on undefined setTimeout

### ISSUE THREAD

**Issue by sjmulder** [stefanpenner/es6-promise#281]
Introduced by commit 18d6dbf9217bb58d741f23e2b8b11b446986df62

Running in a .NET hosted React environment it appears that `setTimeout` isn't available, which causes a runtime error. I had to downgrade to 3.2.1 to make things work again.

I can't currently commit to building a minimal example, sorry.

**Comment by stefanpenner** [comment]
@sjmulder hmm this is strange, confused how that commit changes anything?

**Comment by sjmulder** [comment]
I've created this example of why it happens:

**Comment by stefanpenner** [comment]
Yes but if we are hitting that code-path and erroring because here is no setTimeout. Then we have exhausted all supported forms of async (that I am aware of... maybe the environment you are running in has another?) and this library is unable to function at all.

**Comment by stefanpenner** [comment]
Is native promise (or some other async) available in this Js context?

**Comment by stefanpenner** [comment]
@sjmulder ping?

**Comment by sjmulder** [comment]
Sorry for not getting back earlier. I don't dare say but will do some testing.

**Comment by stefanpenner** [comment]
I don't believe we should make this change.  If there is no `setTimeout` and no other form of async this library is non-function, erroring is ok?

**Comment by sjmulder** [comment]
Fair enough. Sorry for not getting back. It fell off my radar. Sorry if I've been a bother but thanks for your work and continued maintership. Keep it up.

**Comment by stefanpenner** [comment]
> Sorry if I've been a bother

@sjmulder you are absolutely not a bother. I can totally related and emphasize with you issue. 

If i have some time, i'll try to investigate the .NET jscontext environment more, and see if I have a better recommendation.

**Comment by Samywamy10** [comment]
Did we ever come up with a solution for this? Encountering this problem now...
