### ISSUE TITLE
bower repo needs updated to 4.1.0

### ISSUE THREAD

**Issue by flyfishMT** [stefanpenner/es6-promise#285]
Hi, Looks like your bower.json needs updated to 4.1.0 so bower pulls in your latest release. Thanks

**Comment by LeeBurton** [comment]
I second this! There are serious bugs that make es6-promise unusable in 4.0.5, as well as no minified versions! The latest stable version should be released for bower ASAP. not good if this repo is not regularly maintained and we cannot rely on it!

@stefanpenner

**Comment by flyfishMT** [comment]
@LeeBurton you can get it from npm if that is an option.  I switched from bower to npm.

**Comment by LeeBurton** [comment]
We are currently relying on Bower, but looking to switch to Yarn/Webpack. But we currently need Bower...

an update for Bower shouldn't be that difficult, should it...? 😳

**Comment by stefanpenner** [comment]
> There are serious bugs that make es6-promise unusable in 4.0.5

Which bug specifically?

> Hi, Looks like your bower.json needs updated to 4.1.0 so bower pulls in your latest release

Oops. working on a release now.

**Comment by stefanpenner** [comment]
released 4.1.1 to bower and npm

**Comment by LeeBurton** [comment]
Excellent. Thank you :-)
