### ISSUE TITLE
ES6 Promise is not updating my props/state

### ISSUE THREAD

**Issue by khurrams84** [stefanpenner/es6-promise#290]
ES6 Promise is not updating my props/state

**Comment by stefanpenner** [comment]
Sorry, you will need to provide additional information. Examples, etc. The issue as provided is not actionable.

**Comment by khurrams84** [comment]
you can go to https://github.com/khurrams84/ReactApp/blob/master/src/components/events_show.js

When I am changing the checkbox  props are not  getting updated and I am getting same what I got initiallay. 

Hope this gives you better picture.

**Comment by stefanpenner** [comment]
It's not clear to me this is an issue with es6-promise. Can you explain why you believe it is?

**Comment by stefanpenner** [comment]
Sorry, this seems to have gone stale. I would love to help but require the above mentioned information.
