### ISSUE TITLE
ES6 Promise 4.1.0  not work Safari version 9.1 and...

### ISSUE THREAD

**Issue by andalt** [stefanpenner/es6-promise#297]
ES6 Promise 4.1.0  not work in the Safari version 9.1 and es6-promise.map - not Found

new webpack.ProvidePlugin({
    Promise: 'es6-promise'
}),

devtool: 'source-map',

Help

**Comment by stefanpenner** [comment]
we provide the source-maps. Im not sure if webpack does anything automatic here to pickup those maps.

I'm not sure there is much we can do from our side.
