### ISSUE TITLE
typing issue?

### ISSUE THREAD

**Issue by arvind1234** [stefanpenner/es6-promise#300]
I think there might an issue with the typings (Typescript > 2.4.x ) - do correct me if I'm wrong.
But when I return a ES6Promise when a native Promise is expected - I get a TS compiler error saying 
...
"Property '[Symbol.toStringTag]' is missing in type 'Promise<AxiosRequestConfig>'."
...

There is more to the error, but I'm just pasting the last line. So, here I'm returning a ES6Promise<AxiosRequestConfig> when a Promise<AxiosRequestConfig> is expected.

**Comment by stefanpenner** [comment]
It seems like the typings expecting `Symbol.toStringTag` are too strict. Rather they should merely expect something with `then` is returned. Promises are designed to inter-opt entirely on the existing of ` then` function member.
