### ISSUE TITLE
Problem with overriding exising Promise

### ISSUE THREAD

**Issue by slawwan** [stefanpenner/es6-promise#303]
The problem is about how to determine whether you need to override Promise or not
Now main check is comparison of string representation of Promise type if exists
```
let P = local.Promise;

  if (P) {
    var promiseToString = null;
    try {
        promiseToString = Object.prototype.toString.call(P.resolve());
    } catch(e) {
        // silently ignored
    }

    if (promiseToString === '[object Promise]' && !P.cast){
        return;
    }
  }
```
[code in repo](https://github.com/stefanpenner/es6-promise/blob/9cb1f811dabee89d92fab2b7245adcde16f8dcc2/lib/es6-promise/polyfill.js#L29)

Example of bad behavior:
for shorten I will use `runScript` for run [this script](https://github.com/stefanpenner/es6-promise/blob/8a9da19e7466838f80543e3cec9c5bbd3c1e8b50/dist/es6-promise.auto.js)
```
//ie11 Promise is undefined

runScript();
var x = Promise;
x.resolve() instanceof Pomise; //true

runScript(); //redefines Promise because promiseToString === "[object Object]"
x.resolve() instanceof Pomise; //false
```

My real scenario: I use es6-promise polyfill in my application and I have a reference to another library that uses es6-polyfill too.
So, there are two problems:
1. Some library patch globals by using polyfill - I will work on this
2. How es6-promise decides override Promise or not - I do not know of a good solution

I saw interesting solution in [core-js promise polyfill](https://github.com/zloirock/core-js/blob/master/modules/es6.promise.js#L34) but it has similar side effects in firefox:
```fetch("x") instanceof Promise; //false```
because it overrides global existing Promise, but native fetch still uses native Promise

**Comment by josephliccini** [comment]
We are experiencing the same issue. we host another app's code from a CDN to show some widgets.  We are using Angular 4.X, which relies on `window.Promise` being ZoneAwarePromise, from `zone.js`

However, when we are loading their widget later, this seems to be overwriting it causing our Change Detection to break.

They are using `es6-promise`

**Comment by josephliccini** [comment]
Issue I filed against Zone.js: https://github.com/angular/zone.js/issues/891

**Comment by stefanpenner** [comment]
> The problem is about how to determine whether you need to override Promise

This is a tricky problem. Because of this, I typically prefer to avoid globals and prefer to import the exact thing I want.

I'm not sure about a good general purpose problem behind using modules / loaders etc. :(
