### ISSUE TITLE
Broken links to minified files in README.md

### ISSUE THREAD

**Issue by mderriey** [stefanpenner/es6-promise#311]
Hi,

Thanks for the great project. Dropped this to have IE11 support Promises and it worked a treat!

As part of https://github.com/stefanpenner/es6-promise/pull/289, the minified versions were removed from the `dist` directory.
The [_Downloads_ section of the README file](https://github.com/stefanpenner/es6-promise/blob/master/README.md#downloads) has links to both unminified and minified files

The minified links are now broken.

Happy to remove them from the README but wanted to check with you first whether maybe the minified files were removed by mistake from the `dist` folder?

Thanks

**Comment by stefanpenner** [comment]
> Happy to remove them from the README but wanted to check with you first whether maybe the minified files were removed by mistake from the dist folder?

OOPs, fixed!
