### ISSUE TITLE
Promise.prototype.catch IE8  Expected identifier error

### ISSUE THREAD

**Issue by temberature** [stefanpenner/es6-promise#349]
"version": "4.2.6"

```js
  Promise.prototype.catch = function _catch(onRejection) {
    return this.then(null, onRejection);
  };
```

https://www.npmjs.com/package/es3ify-loader
if use webpack, this loader can solve the problem  in some situation

**Comment by stefanpenner** [comment]
Unfortunately, this library cannot help you directly. Ultimately your minifier can be configured to mangle keywords such as `catch` into `value['catch']`.

Doing it here, will not help if the users minifier is not correctly configured as an improperly configured minifier will undo the work.
