### ISSUE TITLE
Why are you using setTimeout(1) instead of setTimeout(0)?

### ISSUE THREAD

**Issue by senaev** [stefanpenner/es6-promise#350]
https://github.com/stefanpenner/es6-promise/blob/314e4831d5a0a85edcb084444ce089c16afdcbe2/lib/es6-promise/asap.js#L79

Why you are waiting one millisecond instead of zero?

**Comment by senaev** [comment]
I am asking because it causes some troubles in environment with faked `Date` and `setTimeout` objects. Would it be harmless if I change value to zero?

**Comment by stefanpenner** [comment]
Ya. Should be harmless, most platforms clamp it to 4ms anyways. So it shouldn’t make much of a difference anyways

**Comment by senaev** [comment]
Made pull-request
https://github.com/stefanpenner/es6-promise/issues/350

**Comment by stefanpenner** [comment]
thanks!
