### ISSUE TITLE
ie9 catch error

### ISSUE THREAD

**Issue by sokolovdm** [stefanpenner/es6-promise#353]
Hello. I'm using vue-cli with es6-promise

babel.config.js:
```
require('es6-promise').polyfill();

module.exports = {
    presets: [
        ['@vue/app', {
            polyfills: [
                'es6.promise',
                'es6.symbol'
             ]
         }]
    ]
}
```
and ie9 crushing project in this place
<img width="1124" alt="Screenshot 2019-07-18 at 12 59 45" src="https://user-images.githubusercontent.com/29097652/61444356-4cacf700-a95c-11e9-9de6-bc1bea1f6122.png">

I saw in yours documentation that 'catch' and 'finally' reserved words in <= ie9. 
How i can fix this?
Thanks.

**Comment by zloirock** [comment]
You should use something like [this transform](https://babeljs.io/docs/en/babel-plugin-transform-member-expression-literals).

**Comment by stefanpenner** [comment]
Yes, I believe many minification tools also offer this.
