### ISSUE TITLE
Uncaught errors dissapearing

### ISSUE THREAD

**Issue by lentinj** [stefanpenner/es6-promise#40]
Here's an example:

```
var Promise = require('es6-promise').Promise;

Promise.resolve().then(function (x) {
    console.log("Doing something");
    throw Error("Agh, it went wrong");
}).catch(function (err) {
    cowsole.log("We had an accident: " + err.message);
});
```

There's no obvious hints that anything went wrong, since I mis-spelt console. Now reading through some comments on the associated article it sounds like the error will be thrown on garbage-collection, but it's not yet. As far as I can see, I can't even implement my own `.catch(done)` to re-throw these errors properly, since any errors within catch will be caught.

So:-
1. Is this a bug, and at some point I can look forward to not worrying about this?
2. Is there a way to stop errors being caught by the promise machinations?
3. Am I being a dolt and missing something obvious?

**Comment by BlueHayes** [comment]
Chrome also has a "Promise inspector" coming which could help in these cases: https://www.youtube.com/watch?v=o9c3U5_8tGY
