### ISSUE TITLE
IE10 Failure (polyfill function not triggered)

### ISSUE THREAD

**Issue by fr4nc0is** [stefanpenner/es6-promise#53]
I've met an issue testing the polyfill under IE10/11

```
SCRIPT5009: « Promise » is undefined
```

Maybe I misunderstand the usage but it seems that the polyfill function `$$es6$promise$polyfill$$default` is not triggered.

Thanks.

**Comment by fyears** [comment]
@stefanpenner 

Hi,

Any future plan to support automatic polyfill in browser?

For instance, in some of my (relatively) small front end website projects, I do not need to use `require.js` to organize the code, but I want to use the awesome Promise features. However, I have to use `requires.js` if I want to use `es6-promise` nowadays. I believe it would be convenient if the library could attach `window.Promise` automatically.
