### ISSUE TITLE
Automatic polyfill

### ISSUE THREAD

**Issue by mariusGundersen** [stefanpenner/es6-promise#59]
It seems this polyfill requires you to call `ES6Promise.polyfill()` before it will work. Wouldn't it be better if it created a global Promise if it cannot find the global Promise?

**Comment by yethee** [comment]
`cast` is part of the specification?
How to prevent overriding the native `Promise` for the latest version of Firefox and Google Chrome?

**Comment by indianburger** [comment]
So we use es6-promise in a javascript file that's a third part script on a page. Being a 3rd party script, we never modify the host page's native objects and this change makes it impossible for us to continue using es6-promise as is.

I wanted to check with you all before I create a fork. Do you have any suggestions for my use case? Would you be open to changing the polyfill behaviour somehow? I'm not super familiar with this code base, but I wonder if you can detect if the module is `require`'ed (browserify) then don't polyfill.

**Comment by stefanpenner** [comment]
> I wanted to check with you all before I create a fork. Do you have any suggestions for my use case? Would you be open to changing the polyfill behaviour somehow? I'm not super familiar with this code base, but I wonder if you can detect if the module is require'ed (browserify) then don't polyfill.

i don't mind shipping promise.polyfil.js (which would auto polyfil) and promise.js (which would be well behaved)

**Comment by indianburger** [comment]
That would be really really sweet

**Comment by stefanpenner** [comment]
> That would be really really sweet

instead of forking, maybe you can contribute that ;)

**Comment by indianburger** [comment]
Happy to give it a shot this weekend. Any pointers as I go through the code?
