### ISSUE TITLE
does not work on Nashorn

### ISSUE THREAD

**Issue by salomvary** [stefanpenner/es6-promise#64]
Due to the lack of `setTimeout` (and all the other alternatives).

(Nashorn is the successor of Rhino).

**Comment by maximenajim** [comment]
Thanks, @stefanpenner, for looking into this.  Have you by chance seen this talk by @william-tran about server-side JavaScript with Nashorn and Spring? https://youtu.be/kVyVyRdxwxE?t=1h17m37s 
They seem to have a working solution for JavaScript promises in Nashorn (unfortunately, this project remains closed-source - awaiting sponsorship).

**Comment by h0ru5** [comment]
any news on this? said talk pointed towards ListenableFuture, but I did not get it to work...

**Comment by stefanpenner** [comment]
@h0ru5 no, as mentioned above we could provide a serializable/thread-safe runtime around nashorn to enable this, but I am unaware of something we can use today.

The introduction of real threads in nashorn, really makes it incompatible with vast amounts of existing JavaScript.

Although the above sounds like fun to implement, I really can't justify the time right now (non of my responsibilities have need for it)
