### ISSUE TITLE
Promise.race - needs to be generic

### ISSUE THREAD

**Issue by altano** [stefanpenner/es6-promise#77]
EDIT: _I split this bug into two, other part at https://github.com/jakearchibald/es6-promise/issues/110_

I might be misreading [the spec](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-promise.race), but I believe the spirit of Note 2, _The race function expects its this value to be a constructor function that supports the parameter conventions of the Promise constructor. It also expects that its this value provides a resolve method._, is to make `Promise.race` generic enough to be used whenever _this_ meets the minimum criteria above.  Is that correct?

If so, es6-promise's `race` is making too many assumptions.  If I call Promise.race.call(X, ...), where X is anything other than an es6-promise, it will blow up b/c `Constructor.resolve(entries[i])` will produce an object that doesn't have the internal `_subscribers` property, and so the call to `subscribe()` in `Promise.race` will throw.  For example, this throws in `subscribe()`:

```javascript
var ES6Promise = require("es6-promise").Promise;
var BlueBirdPromise = require("bluebird");

ES6Promise.race.call(BlueBirdPromise, [3]);
```

**Comment by stefanpenner** [comment]
> var ES6Promise = require("es6-promise").Promise;
> var BlueBirdPromise = require("bluebird");
> 
> ES6Promise.race.call(BlueBirdPromise, [3]);

this is a bug


also, please report issues individually

**Comment by stefanpenner** [comment]
ah this is the *tampering* case I have been punting, https://github.com/tildeio/rsvp.js/issues/271

Well as good as any time to fix it now.

**Comment by stefanpenner** [comment]
this seems like two independent concerns can you split them up?

**Comment by altano** [comment]
> this seems like two independent concerns can you split them up?

Done.  https://github.com/jakearchibald/es6-promise/issues/77 and https://github.com/jakearchibald/es6-promise/issues/110

**Comment by stefanpenner** [comment]
so, ultimately I am unsure how to change this without:

1. hurting performance
2. exploding the byte-size :(
