### ISSUE TITLE
Promise.race keeps obsolete references to child promises

### ISSUE THREAD

**Issue by vandry** [stefanpenner/es6-promise#84]
This might be more of a comment or question than something that absolutely needs to be fixed but I would appreciate your feedback anyway.

When one calls `Promise.race([promise1, promise2])`, `Promise.race` subscribes to the outcome of both promises, meaning it does the internal equivalent of calling `.then()` on each promise (see `lib/es6-promise/promise/race.js` line 101). When one of the two promises resolves, the race promise also resolves, but it remains subscribed to the other promise.

In my use case, I call `Promise.race` in a loop with a promise that rarely resolves and a promise that usually resolves. The latter promise is for work that the application is presently engaged in. The former promise implements a signal for my application to interrupt itself and usually remains pending for a long time, sometimes never resolving at all. What happens is that the former promise collects a lot of useless subscribers, leaking memory. If and when it does resolve, a lot of `onFulfillment` handlers would get called, uselessly resolving race promises that have already been resolved a long time ago.

A simple test application illustrates the issue:

```javascript:
#!/usr/bin/node

var Promise = require("./es6-promise/dist/lib/es6-promise.js").Promise;

var never_resolves = new Promise(function(resolve, reject) {
	return;
});
var already_resolved = Promise.resolve(null);

function run1() {
	return Promise.race([ never_resolves, already_resolved ]);
}

Promise.all(Array.apply(null, Array(10)).map(run1)).then(function(_) {
	console.log(never_resolves._subscribers.length);
});
```

The test script outputs `30`, meaning the `never_resolves` promise has 10 subscribers. They are useless, because the 10 race promises have all already resolved. Those 10 promises can't be garbage-collected.

For this to change, it would have to be possible to unsubscribe to a promise.

Questions/thoughts:

 1. Given that there is no public API for ubsubscribing to a promise and that there won't be one, such an unsubscription function would only be used by `Promise.race()` as far as I can think of. Is it worth it?
 2. I wonder if I can expect browsers' native promise implementations to have a version of the same issue.
 3. Is my use case too weird to support? Is there a better way?

**Comment by stefanpenner** [comment]
This may be related to a recent optimization that when and stuff got. But I haven't had a chance to implement here yet. I will dig in after this week and see if that optimization helps here

**Comment by stefanpenner** [comment]
> Is my use case too weird to support? Is there a better way?

Totally reasonable use-case, unfortunately no unsubscribe is spec'd publicly. I believe though, it to be totally reasonable to implement something like this under the hood, but will require some thinking.

I believe this describes a general issue with Promise.race and promises in general as their is no cancel/unsubscribe yet.

I'm going to close this, because i would consider this purely value add (until promises address this issue) but I will keep it on my mind as time permits for related experimentation.
