### ISSUE TITLE
Can es6 be compiled to a more readable code

### ISSUE THREAD

**Issue by abhijeetkpawar** [stefanpenner/es6-promise#87]
The currently compiled version https://es6-promises.s3.amazonaws.com/es6-promise-2.0.1.js has too many `$` in every function name.

It would be better if these can be simplified.

**Comment by stefanpenner** [comment]
would source maps be sufficient?

**Comment by abhijeetkpawar** [comment]
Not sure.. how source maps can help. 
But, personally I would prefer to have dev-version itself more elegant.

**Comment by stefanpenner** [comment]
if you are interested, you are able to use the es6 code directly, you just need a transpiler.

**Comment by stefanpenner** [comment]
this seems low priority. I think @eventualbuddha did make progress with a prettier transpiler, but i don't recall if that was ever published.

**Comment by stefanpenner** [comment]
rollup has similar output now, as such I may explore using rollup.
